In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings ('ignore')

In [2]:
ls

 Volume in drive C is Acer
 Volume Serial Number is 361B-9495

 Directory of C:\Users\Karthik\Downloads\assignments\logistic regression

24-01-2023  16:09    <DIR>          .
23-01-2023  11:08    <DIR>          ..
24-01-2023  15:18    <DIR>          .ipynb_checkpoints
24-01-2023  16:09            55,274 Bank_LR.ipynb
06-01-2023  20:00         4,610,348 bank-full.csv
06-01-2023  20:00               108 Problem-Statement(Bank_data).txt
               3 File(s)      4,665,730 bytes
               3 Dir(s)  333,945,802,752 bytes free


In [3]:
bank = pd.read_csv("bank-full.csv",";")
bank.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [4]:
bank.shape

(45211, 17)

In [5]:
bank['y'].value_counts()

no     39922
yes     5289
Name: y, dtype: int64

In [6]:
bank.isna().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [7]:
bank.y.replace(to_replace=['no','yes'],value=[0,1],inplace=True)

In [8]:
bank.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [9]:
bank=bank[['y','age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome']]

In [10]:
bank2=pd.get_dummies(bank,columns=['job', 'marital', 'education', 'default','housing',
       'loan', 'contact','month','poutcome'])

In [11]:
bank2

y  age  balance  day  duration  campaign  pdays  previous  job_admin.  \
0      0   58     2143    5       261         1     -1         0           0   
1      0   44       29    5       151         1     -1         0           0   
2      0   33        2    5        76         1     -1         0           0   
3      0   47     1506    5        92         1     -1         0           0   
4      0   33        1    5       198         1     -1         0           0   
...   ..  ...      ...  ...       ...       ...    ...       ...         ...   
45206  1   51      825   17       977         3     -1         0           0   
45207  1   71     1729   17       456         2     -1         0           0   
45208  1   72     5715   17      1127         5    184         3           0   
45209  0   57      668   17       508         4     -1         0           0   
45210  0   37     2971   17       361         2    188        11           0   

       job_blue-collar  ...  month_jun  month_mar  month_may  month_nov  \
0                    0  ...          0          0          1          0   
1                    0  ...          0          0          1          0   
2                    0  ...          0          0          1          0   
3                    1  ...          0          0          1          0   
4                    0  ...          0          0          1          0   
...                ...  ...        ...        ...        ...        ...   
45206                0  ...          0          0          0          1   
45207                0  ...          0          0          0          1   
45208                0  ...          0          0          0          1   
45209                1  ...          0          0          0          1   
45210                0  ...          0          0          0          1   

       month_oct  month_sep  poutcome_failure  poutcome_other  \
0              0          0                 0               0   
1              0          0                 0               0   
2              0          0                 0               0   
3              0          0                 0               0   
4              0          0                 0               0   
...          ...        ...               ...             ...   
45206          0          0                 0               0   
45207          0          0                 0               0   
45208          0          0                 0               0   
45209          0          0                 0               0   
45210          0          0                 0               1   

       poutcome_success  poutcome_unknown  
0                     0                 1  
1                     0                 1  
2                     0                 1  
3                     0                 1  
4                     0                 1  
...                 ...               ...  
45206                 0                 1  
45207                 0                 1  
45208                 1                 0  
45209                 0                 1  
45210                 0                 0  

[45211 rows x 52 columns]

# building a logistic regression model

In [12]:
x =bank2.iloc[:,1::]
y=bank2.iloc[:,0]
print(x)
print(y)

       age  balance  day  duration  campaign  pdays  previous  job_admin.  \
0       58     2143    5       261         1     -1         0           0   
1       44       29    5       151         1     -1         0           0   
2       33        2    5        76         1     -1         0           0   
3       47     1506    5        92         1     -1         0           0   
4       33        1    5       198         1     -1         0           0   
...    ...      ...  ...       ...       ...    ...       ...         ...   
45206   51      825   17       977         3     -1         0           0   
45207   71     1729   17       456         2     -1         0           0   
45208   72     5715   17      1127         5    184         3           0   
45209   57      668   17       508         4     -1         0           0   
45210   37     2971   17       361         2    188        11           0   

       job_blue-collar  job_entrepreneur  ...  month_jun  month_mar  \
0   

In [13]:
x

age  balance  day  duration  campaign  pdays  previous  job_admin.  \
0       58     2143    5       261         1     -1         0           0   
1       44       29    5       151         1     -1         0           0   
2       33        2    5        76         1     -1         0           0   
3       47     1506    5        92         1     -1         0           0   
4       33        1    5       198         1     -1         0           0   
...    ...      ...  ...       ...       ...    ...       ...         ...   
45206   51      825   17       977         3     -1         0           0   
45207   71     1729   17       456         2     -1         0           0   
45208   72     5715   17      1127         5    184         3           0   
45209   57      668   17       508         4     -1         0           0   
45210   37     2971   17       361         2    188        11           0   

       job_blue-collar  job_entrepreneur  ...  month_jun  month_mar  \
0                    0                 0  ...          0          0   
1                    0                 0  ...          0          0   
2                    0                 1  ...          0          0   
3                    1                 0  ...          0          0   
4                    0                 0  ...          0          0   
...                ...               ...  ...        ...        ...   
45206                0                 0  ...          0          0   
45207                0                 0  ...          0          0   
45208                0                 0  ...          0          0   
45209                1                 0  ...          0          0   
45210                0                 1  ...          0          0   

       month_may  month_nov  month_oct  month_sep  poutcome_failure  \
0              1          0          0          0                 0   
1              1          0          0          0                 0   
2              1          0          0          0                 0   
3              1          0          0          0                 0   
4              1          0          0          0                 0   
...          ...        ...        ...        ...               ...   
45206          0          1          0          0                 0   
45207          0          1          0          0                 0   
45208          0          1          0          0                 0   
45209          0          1          0          0                 0   
45210          0          1          0          0                 0   

       poutcome_other  poutcome_success  poutcome_unknown  
0                   0                 0                 1  
1                   0                 0                 1  
2                   0                 0                 1  
3                   0                 0                 1  
4                   0                 0                 1  
...               ...               ...               ...  
45206               0                 0                 1  
45207               0                 0                 1  
45208               0                 1                 0  
45209               0                 0                 1  
45210               1                 0                 0  

[45211 rows x 51 columns]

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn import preprocessing
from sklearn import metrics

In [15]:
model=LogisticRegression()
model.fit(x,y)

LogisticRegression()

In [16]:
model.intercept_

array([-0.27957825])

In [17]:
model.coef_

array([[-2.26295034e-02,  2.37075470e-05, -1.01205749e-02,
         3.89082045e-03, -3.81742205e-01,  2.74093169e-03,
        -1.16021372e-01, -2.56160078e-02, -2.49298003e-01,
        -2.70042511e-02, -9.34490572e-03,  6.33495839e-03,
         1.64361671e-01, -1.62532041e-02, -8.76511461e-02,
         2.97079747e-02, -6.94072787e-02,  2.42373615e-03,
         2.19490016e-03,  1.62337081e-02, -1.71920829e-01,
        -1.23864436e-01, -6.94359869e-02, -2.68720871e-01,
         4.54222397e-02,  1.31830613e-02, -2.59508834e-01,
        -2.00427220e-02,  3.58217310e-01, -6.37768867e-01,
        -8.20625285e-02, -1.97489028e-01,  9.10583656e-02,
         4.97349683e-02, -4.20344890e-01,  4.32882805e-02,
         1.96370152e-02,  2.86280002e-02, -1.48016235e-02,
        -1.46417136e-02, -8.46321342e-02, -5.57082906e-02,
         8.67931279e-02, -4.03736177e-01, -5.69308212e-02,
         9.83212166e-02,  7.42315630e-02, -1.34727142e-01,
        -3.20259740e-02,  3.11064427e-01, -4.23862867e-0

In [18]:
np.round(model.coef_,3)

array([[-0.023,  0.   , -0.01 ,  0.004, -0.382,  0.003, -0.116, -0.026,
        -0.249, -0.027, -0.009,  0.006,  0.164, -0.016, -0.088,  0.03 ,
        -0.069,  0.002,  0.002,  0.016, -0.172, -0.124, -0.069, -0.269,
         0.045,  0.013, -0.26 , -0.02 ,  0.358, -0.638, -0.082, -0.197,
         0.091,  0.05 , -0.42 ,  0.043,  0.02 ,  0.029, -0.015, -0.015,
        -0.085, -0.056,  0.087, -0.404, -0.057,  0.098,  0.074, -0.135,
        -0.032,  0.311, -0.424]])

In [19]:
y_pred=model.predict(x)

In [20]:
y_pred_df=pd.DataFrame({'actual':y,'predicated_values':model.predict(x)})

In [21]:
y_pred_df

actual  predicated_values
0           0                  0
1           0                  0
2           0                  0
3           0                  0
4           0                  0
...       ...                ...
45206       1                  1
45207       1                  0
45208       1                  1
45209       0                  0
45210       0                  0

[45211 rows x 2 columns]

In [22]:
y_pred_df["actual"].value_counts()

0    39922
1     5289
Name: actual, dtype: int64

In [23]:
y_pred_df["predicated_values"].value_counts()

0    43226
1     1985
Name: predicated_values, dtype: int64

In [24]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as ac
confusion_matrix=confusion_matrix(y,y_pred)
print(confusion_matrix)

[[39126   796]
 [ 4100  1189]]


In [25]:
print(classification_report(y,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94     39922
           1       0.60      0.22      0.33      5289

    accuracy                           0.89     45211
   macro avg       0.75      0.60      0.63     45211
weighted avg       0.87      0.89      0.87     45211



# prediction using test and train model

In [26]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=12)
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [27]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94     11990
           1       0.60      0.23      0.33      1574

    accuracy                           0.89     13564
   macro avg       0.75      0.60      0.64     13564
weighted avg       0.87      0.89      0.87     13564

